ESIPFed/sweet

- reprSciProvenance.owl
> ISSUE-26 'opm' namespace prefix no longer exists within reprSciProvenance.owl

- reprDataFormat.ttl
> ISSUE-39 reprDataFormat namespace bug

- reprSciUnits.ttl
This pull request addresses #43
> ISSUE-43 Error in reprSciUnits.ttl

- matrInstrument.ttl
> ISSUE-27 Alignment with SOSA/SSN

- src/humanAgriculture.ttl
Issue addresses #85 and replaces #86 
@smrgeoinfo for context
> ISSUE-85 make Labels for SWEET ontology components more useful

- src/humanCommerce.ttl
- src/humanDecision.ttl
- src/humanEnvirAssessment.ttl
- src/humanEnvirConservation.ttl
- src/humanEnvirControl.ttl
- src/humanEnvirStandards.ttl
- src/humanJurisdiction.ttl
- src/humanKnowledgeDomain.ttl
- src/humanResearch.ttl
- src/humanTechReadiness.ttl
- src/humanTransportation.ttl
testing the branch/update/commit/pull workflow. Seems to be working.
> update rdfs labels for Human related ttl files

- CONTRIBUTING.md
Update the contributions.md instructions.  Please review
> add section on Windows, some clarification

- src/realmBiolBiome.ttl
> Changed axiom AquaticEcosystem hasRealm ONLY Ocean to AquaticEcosystem hasRealm ONLY Hydrosphere

- src/matrMineral.ttl
This PR addresses #128 
@adamancer can you please suggest a term definition for Pyroxene and we can substantiate this pull request. Thank you
> ISSUE-128 Pyroxene misspelled

- src/phenAtmoFront.ttl
> ISSUE-144 'Atmosphere' misspelled in SWEET Ontology Phenomena Atmosphoere Front

- alignments/sweet-ssn-mapping.ttl
> ISSUE-126 SWEET-SSN mappings with individual detail/provenance

- sweetPrefixes.ttl
line 219; 
was a ns collision with ../reprSciComponent -- line 211
> updated ns for .../reprSpaceCoordinate to "sorepscd"

- README.md
https://github.com/ESIPFed/sweet/issues/198
not sure if I should do a direct commit or pull request...
> updated with links to content, per my own suggestion

- src/phenCryo.ttl
- src/realmCryo.ttl
> Fix syntax error in dateTime literals

- src/phenAtmoCloud.ttl
> corrected spelling of noctilucent cloud

- src/realmLandFluvial.ttl
> changed spelling of gulley to gully

- alignments/sweet-dcat-mapping.ttl
- alignments/sweet-ssn-mapping.ttl
Very minor tweak to help this alignment graph play nice - update prefixes to match the ones used elsewhere
> Prefixes in alignment graphs

- src/reprSciUnits.ttl
Added UCUM codes to provide consistent keys for alignment efforts
Fixes #237
> Added UCUM codes in `skos:notation` properties

- src/reprSciUnits.ttl
> UCUM codes for unit prefixes

- src/realmHydroBody.ttl
This issue removes duplicate entry for `dcterms` and adds in content for #135
> ISSUE-135 add "hot spring"

- src/reprSciModel.ttl
> Proposed class for generic act-of-observation

- README.md
- alignments/sweet-dcat-mapping.ttl
- src/realmHydroBody.ttl
> Make prefixes for DC terms and type consistent

- README.md
Previous link was to SWEET ALL page on ESIP COR which wasn't super informative.  This link better reflect what a user might be expecting.
> updated "view on ESIP COR" link

- README.md
I replaced the text that is no longer relevant now that #150 is closed
I think there should be more text about how to use sweet programmatically, but I'll make a new issue for this
> Updating README to reflect fact that the base URL now works

- CITATION.cff
initial draft CITATION.cff file.  Not yet fully populated.  see #256
> Create initial CITATION.cff file

- src/realmCryo.ttl
Moved calf parent from sea ice to just ice
> Moved calf up a level and changed label to ice calf

- src/phenCryo.ttl
- src/realmCryo.ttl
> Issue 103 and Issue 194
